version: '3'

services:

  jupyter:
    build: .
    container_name: jupyter
    ports:
      - "8888:8888"
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    volumes:
      - ./:/work

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: password
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  mysql:
    image: mysql/mysql-server
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      #MYSQL_USER: "test"
      #MYSQL_PASS: "test"
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
